### ISSUE TITLE
Search for a ROOT that has both Phoebe's patch and RooHammerFit working

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/root-curated#1]
We'd like to use the latest ROOT, if possible. If not, we can fall back to ROOT 6.16/00. We need to verify:

- [x] Phoebe's `HistFactory` patch works
- [ ] HAMMER works
- [ ] RD+'s `RooHammerFit` works

**Comment by yipengsun** [comment]
@manuelfs I've moved HAMMER to this repo. @manuelfs could you pull the latest changes of this repo (`root-curated`) and try building HAMMER with:
```
nix build ".#hammer-phys"
```

**Comment by manuelfs** [comment]
Am I in the wrong branch or something?
```
(base) |20:43:44|~/code/root-curated$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From github.com:umd-lhcb/root-curated
   25f8937..929af79  master     -> origin/master
Your configuration specifies to merge with the ref 'refs/heads/test_root_6_16'
from the remote, but no such ref was fetched.

(base) |20:43:51|~/code/root-curated$ git status
On branch test_root_6_16
Your branch is up to date with 'origin/test_root_6_16'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	result

nothing added to commit but untracked files present (use "git add" to track)

(base) |20:44:06|~/code/root-curated$ nix build ".#hammer-phys"
error: attribute 'root_6_12_06' missing

       at /nix/store/nwaaqriz5pd8cm9xi10wax9zdnjm8z8s-source/flake.nix:25:26:

           24|           root_6_16_00 = pkgs.root_6_16_00;
           25|           root_6_12_06 = pkgs.root_6_12_06;
             |                          ^
           26|           root_5_34_38 = pkgs.root_5_34_38;
(use '--show-trace' to show detailed location information)
```

**Comment by yipengsun** [comment]
I think your local `root-curated` has deviated from the official master:
```
Your configuration specifies to merge with the ref 'refs/heads/test_root_6_16'
from the remote, but no such ref was fetched.

(base) |20:43:51|~/code/root-curated$ git status
On branch test_root_6_16
Your branch is up to date with 'origin/test_root_6_16'.

```

You are still on `test_root_6_16` branch instead of `master`. Checkout `master` branch and pull explicitly with `git pull origin master` then try again.

**Comment by manuelfs** [comment]
In `master` I can run `nix build ".#hammer-phys"` without errors.

**Comment by yipengsun** [comment]
ROOT 6.24/04 is out, and `nixpkgs`'s upstream package will be updated to that version soon ([pull request](https://github.com/NixOS/nixpkgs/pull/136016)). 

Should we update now? My initial take is that given we are still working on making fitter work, we defer this until we reach a conclusion on the fitter study. On the other hand, 6.24/04 is a bugfix release so it might be desirable to work with a version of ROOT that has fewer known bugs?
