### ISSUE TITLE
Compiling ROOT in macOS Catalina and Big Sur

### ISSUE THREAD

**Issue by Svende** [umd-lhcb/root-curated#3]
According to the release notes https://root.cern/releases/release-62206/ ROOT 6.22/06 should work with Big Sur, but I am running into problems when I compile it. This is what I do (following https://root.cern/install/#build-from-source):
1. `git clone --branch v6-22-00-patches https://github.com/root-project/root.git root_src`
2. `mkdir root_build root_install && cd root_build`
3. `cmake -DCMAKE_INSTALL_PREFIX=../root_install ../root_src`
4. `cmake --build . -- install -j4`
The output log is attached. 
[Log_Root62206_BigSur.txt](https://github.com/umd-lhcb/root-curated/files/6697413/Log_Root62206_BigSur.txt)
@manuelfs @yipengsun Please let me know what other info you need from me, thanks!

**Comment by Svende** [comment]
With ROOT 6.24/00 on Big Sur it compiles fine

**Comment by manuelfs** [comment]
Thanks. Can you also list the other combinations that worked and did not work (eg, 6.12, 6.24) even if you don't have the log files? And do you have the log file with the compilation errors of 6.24 + patches?

**Comment by Svende** [comment]
Yes I was going to do that on a different issue with the patches included.

**Comment by Svende** [comment]
Before I tried with **ROOT v6-12-04 with the patch** as this is the same ROOT version used in the patch `Patches_July2020_ROOT-6.12.04.zip` by Manuel (https://twiki.cern.ch/twiki/bin/viewauth/LHCbPhysics/HistFactoryInfo):

- First I had problems with step 3 above, Yipeng helped me to fix that by running it with: `-Dimt=OFF`instead
- Still in step 4 I had the following output log:

    ```
    LZ4 download command succeeded. See also /Users/svendebraun/root_build/LZ4-prefix/src/LZ4-stamp/LZ4-download-*.log
    [ 34%] No update step for 'LZ4'
    [ 34%] No patch step for 'LZ4'
    [ 34%] Performing configure step for 'LZ4'
    [ 34%] Building CXX object interpreter/llvm/src/lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/TypeRecordMapping.cpp.o
    [ 34%] Creating directories for 'FREETYPE'
    [ 34%] Performing download step (verify and extract) for 'FREETYPE'
    -- FREETYPE download command succeeded. See also /Users/svendebraun/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-download-*.log
    [ 34%] No update step for 'FREETYPE'
    [ 34%] No patch step for 'FREETYPE'
    [ 34%] Performing configure step for 'FREETYPE'
    [ 34%] Building CXX object interpreter/llvm/src/lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/TypeSerializer.cpp.o
    CMake Error at /Users/svendebraun/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-RelWithDebInfo.cmake:49 (message):
     Command failed: 2
      './configure' '--prefix' '/Users/svendebraun/root_build/FREETYPE-prefix' '--with-pic' '--disable-shared' '--with-png=no' '--with-bzip2=no' '--with-harfbuzz=no' 'CC=/Library/Developer/CommandLineTools/usr/bin/cc' 'CFLAGS=-O'
     See also
      /Users/svendebraun/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-*.log
    make[2]: *** [FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure] Error 1
    make[1]: *** [CMakeFiles/FREETYPE.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/SubtargetEmitter.cpp.o
    -- LZ4 configure command succeeded. See also /Users/svendebraun/root_build/LZ4-prefix/src/LZ4-stamp/LZ4-configure-*.log
    [ 34%] Performing build step for 'LZ4'
    [ 34%] Building CXX object interpreter/llvm/src/lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/TypeStreamMerger.cpp.o
    -- LZ4 build command succeeded. See also /Users/svendebraun/root_build/LZ4-prefix/src/LZ4-stamp/LZ4-build-*.log
    [ 34%] Performing install step for 'LZ4'
    -- LZ4 install command succeeded. See also /Users/svendebraun/root_build/LZ4-prefix/src/LZ4-stamp/LZ4-install-*.log
    [ 34%] Completed 'LZ4'
    [ 34%] Built target LZ4
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/SubtargetFeatureInfo.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/TableGen.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/TypeTableCollection.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/Types.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o
    [ 34%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
    [ 34%] Built target LLVMDebugInfoCodeView
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o
    [ 34%] Building CXX object interpreter/llvm/src/utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o
    [ 34%] Built target obj.llvm-tblgen
    make: *** [all] Error 2
    ```

**Comment by Svende** [comment]
Using **ROOT 6.22.08 with the same patch**  I get the following error:
[Log_Root62206_BigSur_patch.txt](https://github.com/umd-lhcb/root-curated/files/6697604/Log_Root62206_BigSur_patch.txt)

**Comment by Svende** [comment]
Using **ROOT 6.24.00 with the same patch** I get a very similar  error:
[Log_Root62400_BigSur_patch.txt](https://github.com/umd-lhcb/root-curated/files/6701682/Log_Root62400_BigSur_patch.txt)

**Comment by manuelfs** [comment]
I tried to compile a ROOT 6.24/00 in Catalina (I had 6.22/06 compiled from source)
```
cd ~/code/root/
git pull
git tag -l
git checkout v6-24-00
cd ../build_root/
cmake -DCMAKE_INSTALL_PREFIX=../install_root/ ../root
cmake --build . -- install -j4
```

But got errors
```
-- Clang version: 9.0.1
-- Cling version (from VERSION file): ROOT_0.9~dev
-- Cling will look for C++ headers in '/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1' at runtime.
-- And if not found, will invoke: '/Library/Developer/CommandLineTools/usr/bin/c++ ' for them.
-- Cling version (from VERSION file): ROOT_0.9~dev
CMake Error at interpreter/llvm/src/cmake/modules/AddLLVM.cmake:432 (add_library):
  add_library cannot create target "obj.clingInterpreter" because another
  target with the same name already exists.  The existing target is created
  in source directory
  "/Users/manuelf/code/root/interpreter/cling/lib/Interpreter".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  interpreter/cling/CMakeLists.txt:413 (llvm_add_library)
  interpreter/cling/lib/Interpreter/CMakeLists.txt:59 (add_cling_library)


CMake Error at interpreter/llvm/src/cmake/modules/AddLLVM.cmake:472 (add_library):
  add_library cannot create target "clingInterpreter" because another target
  with the same name already exists.  The existing target is a static library
  created in source directory
  "/Users/manuelf/code/root/interpreter/cling/lib/Interpreter".  See
  documentation for policy CMP0002 for more details.
```

Perhaps it is colliding with my previous compilation?

**Comment by manuelfs** [comment]
That error was due to being inside a nix shell. I tried compiling 6.24/00 outside, and it started fine, but then it had a fatal error at 80%
```
/Users/manuelf/code/build_root/include/TSQLiteResult.h:17:2: fatal error: module file '/Users/manuelf/code/build_root/lib/Darwin.pcm' is out of date and needs to be rebuilt: signature mismatch
#include <sqlite3.h>
 ^
/Users/manuelf/code/build_root/include/TSQLiteResult.h:17:2: note: imported by module 'SQLite3' in '/Users/manuelf/code/build_root/lib/SQLite3.pcm'
```
[catalina_root_6.24.00.log](https://github.com/umd-lhcb/root-curated/files/6710785/catalina_root_6.24.00.log)

**Comment by yipengsun** [comment]
Try to disable `mysql`:

https://github.com/umd-lhcb/root-curated/blob/f07459c1ec09f7843a38ac55f374bf0e86ca67d9/nix/root/default.nix#L103
https://github.com/umd-lhcb/root-curated/blob/f07459c1ec09f7843a38ac55f374bf0e86ca67d9/nix/root/default.nix#L112

**Comment by manuelfs** [comment]
With `squilte` off, it got to 100%, but then it somehow still gave the same error? I wonder whether something needs to be cleaned up
```
cmake -DCMAKE_INSTALL_PREFIX=../install_root/ -Dsqlite=OFF ../root
cmake --build . -- install -j4 

...

[100%] Built target HistFactory
Scanning dependencies of target hist2workspace
[100%] Built target onepcm
[100%] Generating tutorials/hsimple.root
[100%] Building CXX object roofit/histfactory/CMakeFiles/hist2workspace.dir/src/hist2workspace.cxx.o
[100%] Building CXX object roofit/histfactory/CMakeFiles/hist2workspace.dir/src/MakeModelAndMeasurements.cxx.o
<<< cling interactive line includer >>>: fatal error: module file '/Users/manuelf/code/build_root/lib/Darwin.pcm' is out of date and needs to be rebuilt: signature mismatch
<<< cling interactive line includer >>>: note: imported by module 'SQLite3' in '/Users/manuelf/code/build_root/lib/SQLite3.pcm'
Failed to load module SQLite3
Assertion failed: (Result.is(tok::eof) && "Preprocessor did not set tok:eof"), function LexTokenInternal, file /Users/manuelf/code/root/interpreter/llvm/src/tools/clang/lib/Lex/Lexer.cpp, line 3740.
/bin/sh: line 1: 21531 Abort trap: 6           DYLD_LIBRARY_PATH=/Users/manuelf/code/build_root/lib:/Users/manuelf/code/build_root/lib ROOTIGNOREPREFIX=1 ROOT_HIST=0 /Users/manuelf/code/build_root/bin/root.exe -l -q -b -n -x hsimple.C -e return
make[2]: *** [tutorials/hsimple.root] Error 134
make[1]: *** [CMakeFiles/hsimple.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../bin/hist2workspace
[100%] Built target hist2workspace
make: *** [all] Error 2
```

**Comment by yipengsun** [comment]
This is weird. Google came up mostly empty. Maybe ask on root forum?

**Comment by manuelfs** [comment]
I googled the `Darwin.pcm' is out of date and needs to be rebuilt: signature mismatch` and found this [post](https://stackoverflow.com/questions/40121624/pcm-is-out-of-date-and-needs-to-be-rebuilt) pretty much confirming that I just needed to clean up the installation. I removed the `build` and `install` folders, and it compiled! 
```
rm -rf install_root build_root
mkdir install_root build_root
cd build_root/
cmake -DCMAKE_INSTALL_PREFIX=../install_root/ -Dsqlite=OFF -Dmysql=OFF ../root 
cmake --build . -- install -j6
```
Except that I was still in tag `v6-22-06`. But I suspected the problem I had seen in `v6-24-00` was due to the same cause, so I cleaned up the installation, checked out `v6-24-00` and... it also compiled! 🎉🎉

Next, I'll try the patches in this tag, either mine or Julian's, if we get those.

**Comment by manuelfs** [comment]
Annoyingly, in `v6-24-00` I get the same error in `plot_scripts` as @Svende when compiled outside of nix 😞
```
dyld: Library not loaded: @rpath/libCore.so
  Referenced from: /Users/manuelf/code/plot_scripts/./run/core/generate_baby.exe
  Reason: image not found
make: *** [dummy_baby.all] Abort trap: 6
```

**Comment by manuelfs** [comment]
I'm not sure why I didn't have the `dyld: Library not loaded: @rpath/libCore.so` error before, but apparently, starting with macOS 10.11, the value of environmental variables is stripped in scripts https://root-forum.cern.ch/t/dyld-not-loading-when-running-root-within-python-script/27747

I tested that this was the case by including a `print(os.getenv('$DYLD_LIBRARY_PATH'))` statement in `compile.py`, and it returned `None` (while it is `/Users/manuelf/code/build_root/lib` before running the script). I also tried running `./run/core/generate_baby.exe` directly in the terminal as opposed to inside the script, and it ran without problems.

The post above talks about setting `rpath` or something, so I'm trying to compile ROOT with the flags that I used in the past, which included `rpath`
```
cmake -DCMAKE_INSTALL_PREFIX=../install_root/ -Dsqlite=OFF -Dmysql=OFF -Dx11=ON  -Droofit=ON  -Dmt=ON -Dminuit2=ON -Dccache=ON -Dlibcxx=ON -Drpath=ON ../root 
cmake --build . -- install -j6
```

PS I had always set `LD_LIBRARY_PATH` in Macs and it worked fine, but [this post](https://root-forum.cern.ch/t/error-loading-libraries/28819) says that it should be `DYLD_LIBRARY_PATH` instead, so I'm setting that as well

**Comment by manuelfs** [comment]
It worked!

After recompiling ROOT 6.24/00 with the flags in the previous post (which include `-Drpath=ON`), I was able to compile `plot_scripts` without the `dyld: Library not loaded` error!

@Svende should try this too, including `rm -rf install_root build_root` for safety. Also, since you need to recompile, you should clone our fork (https://github.com/umd-lhcb/root), which actually does not take that much time to download

**Comment by yipengsun** [comment]
I'll document this ROOT compilation procedure in README too.

**Comment by yipengsun** [comment]
I documented the compilation procedure at: https://github.com/umd-lhcb/root-curated#compiling-root-without-nix-on-macos

Could you take a look and see if you agree? If so, please close this issue.

**Comment by Svende** [comment]
these flags also work for me, thanks!

**Comment by manuelfs** [comment]
@Svende Great! Did you check that you can compile `plot_scripts` now?

Also, can you try if the HistFactory patches I committed to 6.24/00 compile for you?
https://github.com/umd-lhcb/root/tree/2db8078491ad9e1f5ac571f92ee37b4c2cd8e50e

**Comment by yipengsun** [comment]
BTW, in the README, I already changed source of `root` to our fork.

**Comment by Svende** [comment]
@manuelfs Sorry I wasn't specific enough before: Yes I tried compiling `plot_scripts` and it worked (it worked already last Thrusday after trying out a bunch of things together).
Also I the compilation of ROOT 6.24/00 including the HistFactory patches worked for me! (I missed before that the patch was already included in those instructions https://github.com/umd-lhcb/root-curated#compiling-root-without-nix-on-macos). I am running now the `HistFactDstTauDemo.C` to see if it works!
Thank you very much for fixing all of that!!!

**Comment by manuelfs** [comment]
> @manuelfs Sorry I wasn't specific enough before: Yes I tried compiling `plot_scripts` and it worked (it worked already last Thrusday after trying out a bunch of things together).

Do you mean that you were able to compile `plot_scripts` outside of nix on Thursday? Do you know what you did?

> Also I the compilation of ROOT 6.24/00 including the HistFactory patches worked for me! (I missed before that the patch was already included in those instructions https://github.com/umd-lhcb/root-curated#compiling-root-without-nix-on-macos). I am running now the HistFactDstTauDemo.C to see if it works!

🎉🤞

**Comment by Svende** [comment]
> Do you mean that you were able to compile `plot_scripts` outside of nix on Thursday? Do you know what you did?

Yes, I think we changed a bunch of things and at some point it worked, I don't remember what though.
