### ISSUE TITLE
Using `direnv` in macOS

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/root-curated#6]
I followed the instructions to set up `direnv` from [here](https://github.com/umd-lhcb/root-curated/tree/2a75091c156cea683d3ab18ed4d43db1963575b0#automate-nix-develop-by-installing-direnv) and the automatic switching to the nix shell when going to `lhcb-ntuples` did not occur after rebooting.

I then executed the commands directly in the terminal without the rebooting
```
eval "$(direnv hook bash)"
source $HOME/.nix-profile/share/nix-direnv/direnvrc
```
and it did try to go to the nix shell, but had an error after the `allow` and every time after
```
(base) |16:10:36|~/code/root-curated$ cd ../lhcb-ntuples-gen/
direnv: error /Users/manuelf/code/lhcb-ntuples-gen/.envrc is blocked. Run `direnv allow` to approve its content

(base) |16:10:38|~/code/lhcb-ntuples-gen$ direnv allow
direnv: loading ~/code/lhcb-ntuples-gen/.envrc
direnv: using flake
error: 'print-dev-env' is not a recognised command
Try '/nix/store/zzi705n85r031raw4jw90ikbna5kwjvh-nix-2.3.12/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/zzi705n85r031raw4jw90ikbna5kwjvh-nix-2.3.12/bin/nix --help' for more information.
direnv: renewed cache
direnv: export +XDG_DATA_DIRS

(base) |16:10:55|~/code/lhcb-ntuples-gen$ cd ../
direnv: unloading

(base) |16:11:15|~/code$ cd lhcb-ntuples-gen/
direnv: loading ~/code/lhcb-ntuples-gen/.envrc
direnv: using flake
error: 'print-dev-env' is not a recognised command
Try '/nix/store/zzi705n85r031raw4jw90ikbna5kwjvh-nix-2.3.12/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/zzi705n85r031raw4jw90ikbna5kwjvh-nix-2.3.12/bin/nix --help' for more information.
direnv: renewed cache
direnv: export +XDG_DATA_DIRS
```

Since the set up is not permanent, it doesn't try to enter the `lhcb-ntuples-gen` nix shell automaticallly when I start a new shell.

**Comment by manuelfs** [comment]
In `~/.nix-profile/share/nix-direnv/direnvrc` changed the nix that is loading to my local one
```
NIX_BIN_PREFIX=/nix/var/nix/profiles/default/bin/
```

It then automatically loaded the environment defined in the nix flake, but without opening a new shell

**Comment by yipengsun** [comment]
Can you try the following:

1. Go to `~/.config/nixpkgs/overlays`. If the directory doesn't exist, create it with `mkdir -p`
2. Create a `base.nix` with the following content:
    
    ```nix
    final: prev:

    {
      nix-direnv = prev.nix-direnv.override { enableFlakes = true; };
    }
    ```

3. Install `nix-direnv` again with `nix-env -iA nixpkgs.nix-direnv`

**Comment by manuelfs** [comment]
This procedure worked!

**Comment by yipengsun** [comment]
Let's document it in the README and close this issue then!

**Comment by yipengsun** [comment]
And you don't need to edit the `direnvrc` what-so-ever right?

**Comment by manuelfs** [comment]
Nope, my `$HOME/.nix-profile/share/nix-direnv/direnvrc` automatically selected nix 2.4 (`NIX_BIN_PREFIX=/nix/store/2z11sw52v293c5x89b2dkqsj2cc5m86w-nix-2.4pre20210601_5985b8b/bin/`)
